/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Services */
        get: operations["list_services_api_v1_services_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/convert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Convert */
        get: operations["convert_api_v1_convert_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/c/{short_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Open Share */
        get: operations["open_share_api_v1_c__short_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CacheInfo */
        CacheInfo: {
            /** Hit */
            hit: boolean;
            /** Ttl Seconds */
            ttl_seconds: number;
        };
        /** ConvertResponse */
        ConvertResponse: {
            source: components["schemas"]["SourceContent"];
            /** Targets */
            targets: {
                [key: string]: components["schemas"]["TargetResult"];
            };
            cache: components["schemas"]["CacheInfo"];
            share?: components["schemas"]["ShareInfo"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Redis */
            redis: boolean;
            /** Postgres */
            postgres: boolean;
        };
        /** ServiceInfo */
        ServiceInfo: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Capabilities */
            capabilities: ("track" | "album" | "artist")[];
        };
        /** ServicesResponse */
        ServicesResponse: {
            /** Services */
            services: components["schemas"]["ServiceInfo"][];
        };
        /** ShareInfo */
        ShareInfo: {
            /** Id */
            id: string;
            /** Url */
            url: string;
        };
        /** SourceContent */
        SourceContent: {
            /** Service */
            service: string;
            /**
             * Type
             * @enum {string}
             */
            type: "track" | "album" | "artist";
            /** Id */
            id: string;
            /** Url */
            url: string;
            /** Title */
            title: string;
            /** Artists */
            artists: string[];
            /** Album */
            album?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Isrc */
            isrc?: string | null;
            /** Upc */
            upc?: string | null;
            /**
             * Artwork
             * @default
             */
            artwork: string;
        };
        /** TargetResult */
        TargetResult: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "ok_low" | "not_found" | "error";
            /** Url */
            url?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Match */
            match?: ("isrc" | "upc" | "metadata") | null;
            /** Message */
            message?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_services_api_v1_services_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServicesResponse"];
                };
            };
        };
    };
    convert_api_v1_convert_get: {
        parameters: {
            query: {
                /** @description Music-service URL */
                url: string;
                /** @description Comma-separated list of target service ids */
                targets?: string | null;
                /** @description If true, produce a share short-id */
                share?: boolean;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConvertResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_share_api_v1_c__short_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                short_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConvertResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
