{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "linkhop.fullname" . }}
  labels:
    {{- include "linkhop.labels" . | nindent 4 }}
type: Opaque
stringData:
  LINKHOP_DATABASE_URL: {{ required "config.databaseUrl is required" .Values.config.databaseUrl | quote }}
  LINKHOP_REDIS_URL: {{ include "linkhop.redisUrl" . | quote }}
  LINKHOP_SPOTIFY_CLIENT_ID: {{ .Values.secrets.spotifyClientId | quote }}
  LINKHOP_SPOTIFY_CLIENT_SECRET: {{ .Values.secrets.spotifyClientSecret | quote }}
  LINKHOP_TIDAL_CLIENT_ID: {{ .Values.secrets.tidalClientId | quote }}
  LINKHOP_TIDAL_CLIENT_SECRET: {{ .Values.secrets.tidalClientSecret | quote }}
{{- end }}
