"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-04-18 20:36:19.219062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key_prefix', sa.String(length=12), nullable=False),
    sa.Column('key_hash', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rate_limit_override', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_prefix')
    )
    op.create_table('conversions',
    sa.Column('short_id', sa.String(length=12), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_service', sa.String(length=32), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('last_access_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('short_id'),
    sa.UniqueConstraint('source_service', 'source_type', 'source_id', name='uq_conversion_source')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversions')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
